name: C program test workflow

# Define trigger event
on: [push]

# Job to run in parallel by default, each runs steps in sequence
jobs:

  # Job to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"