name: C program test workflow

# Define trigger event
on: [push]

# Job to run in parallel by default, each runs steps in sequence
jobs:

  # Job to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello, world!"

  # Job to build and test the C program
  build-and-test:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:

      # Use github.com/actions/checkout to check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Install necessary packages
      - name: Install dependencies
        run: sudo apt install -y build-essential python3
      
      - run: pwd

      # Run the test
      - name: Run test
        run: python3 test.py

